spring.datasource:
  url: jdbc:mariadb://localhost:3306/Wetsuits
  username: root
  password: Iv5eekae
  driver-class-name: org.mariadb.jdbc.Driver
spring.jpa:
  hibernate.ddl-auto: validate
  properties.hibernate:
    dialect: org.hibernate.dialect.MariaDB103Dialect
    show_sql: true
    format_sql: true
    query.substitutions: true